version: '3.8'

services:
  ubuntu_os:
    build:
      context: .
      dockerfile: Dockerfile.ubuntu
    container_name: osTelegram
    volumes:
      - ./source:/source
    ports:
      - "2222:22" 
    tty: true